//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 02:47:35 PM EDT 
//


package ca.on.wsib.tcm.ws.model;

import javax.activation.DataHandler;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlMimeType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddClaimsVersion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddClaimsVersion"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="documentId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="claimMetaData" type="{http://ws.tcm.wsib.on.ca/}AddClaimsVersionClaimsMetaData"/&gt;
 *         &lt;element name="integrationMetaData" type="{http://ws.tcm.wsib.on.ca/}AddClaimsVersionIntegrationMetaData"/&gt;
 *         &lt;element name="fileInfo" type="{http://ws.tcm.wsib.on.ca/}AddClaimsVersionFileInfo"/&gt;
 *         &lt;element name="fileContent" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="transactionID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddClaimsVersion", propOrder = {
    "documentId",
    "claimMetaData",
    "integrationMetaData",
    "fileInfo",
    "fileContent",
    "transactionID"
})
public class AddClaimsVersion {

    protected int documentId;
    @XmlElement(required = true)
    protected AddClaimsVersionClaimsMetaData claimMetaData;
    @XmlElement(required = true)
    protected AddClaimsVersionIntegrationMetaData integrationMetaData;
    @XmlElement(required = true)
    protected AddClaimsVersionFileInfo fileInfo;
    @XmlElement(required = true)
    @XmlMimeType("application/octet-stream")
    protected DataHandler fileContent;
    @XmlElement(required = true)
    protected String transactionID;

    /**
     * Gets the value of the documentId property.
     * 
     */
    public int getDocumentId() {
        return documentId;
    }

    /**
     * Sets the value of the documentId property.
     * 
     */
    public void setDocumentId(int value) {
        this.documentId = value;
    }

    /**
     * Gets the value of the claimMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link AddClaimsVersionClaimsMetaData }
     *     
     */
    public AddClaimsVersionClaimsMetaData getClaimMetaData() {
        return claimMetaData;
    }

    /**
     * Sets the value of the claimMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddClaimsVersionClaimsMetaData }
     *     
     */
    public void setClaimMetaData(AddClaimsVersionClaimsMetaData value) {
        this.claimMetaData = value;
    }

    /**
     * Gets the value of the integrationMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link AddClaimsVersionIntegrationMetaData }
     *     
     */
    public AddClaimsVersionIntegrationMetaData getIntegrationMetaData() {
        return integrationMetaData;
    }

    /**
     * Sets the value of the integrationMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddClaimsVersionIntegrationMetaData }
     *     
     */
    public void setIntegrationMetaData(AddClaimsVersionIntegrationMetaData value) {
        this.integrationMetaData = value;
    }

    /**
     * Gets the value of the fileInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AddClaimsVersionFileInfo }
     *     
     */
    public AddClaimsVersionFileInfo getFileInfo() {
        return fileInfo;
    }

    /**
     * Sets the value of the fileInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddClaimsVersionFileInfo }
     *     
     */
    public void setFileInfo(AddClaimsVersionFileInfo value) {
        this.fileInfo = value;
    }

    /**
     * Gets the value of the fileContent property.
     * 
     * @return
     *     possible object is
     *     {@link DataHandler }
     *     
     */
    public DataHandler getFileContent() {
        return fileContent;
    }

    /**
     * Sets the value of the fileContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataHandler }
     *     
     */
    public void setFileContent(DataHandler value) {
        this.fileContent = value;
    }

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }

}
