//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 02:47:35 PM EDT 
//


package ca.on.wsib.tcm.ws.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClaimsDataBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClaimsDataBean"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="claimsMetaData" type="{http://ws.tcm.wsib.on.ca/}claimsMetaData" minOccurs="0"/&gt;
 *         &lt;element name="integrationMetaData" type="{http://ws.tcm.wsib.on.ca/}integrationMetaData" minOccurs="0"/&gt;
 *         &lt;element name="fileInfo" type="{http://ws.tcm.wsib.on.ca/}fileInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClaimsDataBean", propOrder = {
    "claimsMetaData",
    "integrationMetaData",
    "fileInfo"
})
public class ClaimsDataBean {

    protected ClaimsMetaData claimsMetaData;
    protected IntegrationMetaData integrationMetaData;
    protected FileInfo fileInfo;

    /**
     * Gets the value of the claimsMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimsMetaData }
     *     
     */
    public ClaimsMetaData getClaimsMetaData() {
        return claimsMetaData;
    }

    /**
     * Sets the value of the claimsMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimsMetaData }
     *     
     */
    public void setClaimsMetaData(ClaimsMetaData value) {
        this.claimsMetaData = value;
    }

    /**
     * Gets the value of the integrationMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link IntegrationMetaData }
     *     
     */
    public IntegrationMetaData getIntegrationMetaData() {
        return integrationMetaData;
    }

    /**
     * Sets the value of the integrationMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegrationMetaData }
     *     
     */
    public void setIntegrationMetaData(IntegrationMetaData value) {
        this.integrationMetaData = value;
    }

    /**
     * Gets the value of the fileInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FileInfo }
     *     
     */
    public FileInfo getFileInfo() {
        return fileInfo;
    }

    /**
     * Sets the value of the fileInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileInfo }
     *     
     */
    public void setFileInfo(FileInfo value) {
        this.fileInfo = value;
    }

}
