//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 02:47:35 PM EDT 
//


package ca.on.wsib.tcm.ws.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DownloadClaimsDocumentResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DownloadClaimsDocumentResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="claimsDocument" type="{http://ws.tcm.wsib.on.ca/}ClaimsDocumentBean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DownloadClaimsDocumentResponse", propOrder = {
    "claimsDocument"
})
public class DownloadClaimsDocumentResponse {

    protected ClaimsDocumentBean claimsDocument;

    /**
     * Gets the value of the claimsDocument property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimsDocumentBean }
     *     
     */
    public ClaimsDocumentBean getClaimsDocument() {
        return claimsDocument;
    }

    /**
     * Sets the value of the claimsDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimsDocumentBean }
     *     
     */
    public void setClaimsDocument(ClaimsDocumentBean value) {
        this.claimsDocument = value;
    }

}
