package ca.on.wsib.cc.webservices.createclaim;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-03-22T13:23:31.300-04:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://wsib.on.ca/cc/webservices/createclaim/kofax/service", name = "ICreateClaimAPIPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ICreateClaimAPIPortType {

    @WebMethod
    @RequestWrapper(localName = "createDraftClaim", targetNamespace = "http://wsib.on.ca/cc/webservices/createclaim/kofax/service", className = "ca.on.wsib.cc.webservices.createclaim.CreateDraftClaim")
    @ResponseWrapper(localName = "createDraftClaimResponse", targetNamespace = "http://wsib.on.ca/cc/webservices/createclaim/kofax/service", className = "ca.on.wsib.cc.webservices.createclaim.CreateDraftClaimResponse")
    @WebResult(name = "return", targetNamespace = "http://wsib.on.ca/cc/webservices/createclaim/kofax/service")
    public ca.on.wsib.cc.webservices.createclaim.CreateClaimResponse createDraftClaim(
        @WebParam(name = "request", targetNamespace = "http://wsib.on.ca/cc/webservices/createclaim/kofax/service")
        ca.on.wsib.cc.webservices.createclaim.Claim request,
        @WebParam(name = "authentication", targetNamespace = "http://guidewire.com/ws/soapheaders", header = true)
        Authentication gwAuthentication,
        @WebParam(name = "locale", targetNamespace = "http://guidewire.com/ws/soapheaders", header = true)
        Locale gwLocale
    );
}
